=== cbig/zupport/zupport/resources/DocSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="docs" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="docs">

    

    


    <xsd:element name="Documentation" type="DocType"></xsd:element>


    <xsd:complexType name="DocType">
    	<xsd:sequence>
    		<xsd:element name="Dataset" minOccurs="1" maxOccurs="1">
    			<xsd:complexType>
    				<xsd:sequence>
                        <xsd:element name="Name" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
                        <xsd:element name="Administrator" type="xsd:string" minOccurs="0" maxOccurs="1">
    		</xsd:element>
                        <xsd:element name="Updated" type="xsd:dateTime" minOccurs="0" maxOccurs="1">
    		</xsd:element>
                        <xsd:element name="Publicity" minOccurs="0" maxOccurs="1">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:string">
    					<xsd:enumeration value="Julkinen"></xsd:enumeration>
    					<xsd:enumeration value="Puolijulkinen"></xsd:enumeration>
    					<xsd:enumeration value="Ei-julkinen"></xsd:enumeration>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
                        <xsd:element name="PlannedUsage" type="xsd:string" minOccurs="0" maxOccurs="1">
    		</xsd:element>
                        <xsd:element name="Characteristics" type="xsd:string" minOccurs="0" maxOccurs="1">
    		</xsd:element>
                        <xsd:element name="AnalysisUsage" type="xsd:string" minOccurs="0" maxOccurs="1">
    		</xsd:element>
                        <xsd:element name="Description" type="xsd:string" minOccurs="0" maxOccurs="1">
    		</xsd:element>
                    </xsd:sequence>
    			</xsd:complexType>
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== cbig/zupport/zupport/data/docs.xml
<?xml version="1.0" encoding="UTF-8"?>
<Documentation xmlns="docs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="docs ../resources/DocSchema.xsd ">
  <Dataset>
    <Name>Arvokkaat kallioalueet</Name>
    <Administrator>SYKE</Administrator>
    <Updated>2009-12-01T16:00:00</Updated>
    <Publicity>Julkinen</Publicity>
    <PlannedUsage>Päätöksenteon tukena maa-aineislain ja rakennuslain mukaisia ratkaisuja tehtäessä</PlannedUsage>
    <Characteristics>Ei juridista asemaa</Characteristics>
    <AnalysisUsage>arvoa kuvaava ja/tai rakennepiirteitä sisältävä</AnalysisUsage>
    <Description>Aineistolla on keskeinen merkityksensä myös maankäytön suunnittelussa, mutta sillä ei ole kuitenkaan juridista asemaa.</Description>
  </Dataset>
</Documentation>
